### ISSUE TITLE
Discord Webhook Command Logs (file attached)

### ISSUE THREAD

**Issue by crywink** [Sceleratis/Adonis-Plugins#1]
A simple & easy-to-use plugin that lets you log your commands to a Discord webhook.

[Server- Discord Webhook.txt](https://github.com/Sceleratis/Adonis-Plugins/files/4833485/Server-.Discord.Webhook.txt)

**Comment by crywink** [comment]
Updated: [Server- Discord Webhook.txt](https://github.com/Sceleratis/Adonis-Plugins/files/4833914/Server-.Discord.Webhook.txt)

The plugin now connects the CommandRan event directly rather than using `service.HookEvent`.

**Comment by Sceleratis** [comment]
Adding
